server: 
  port: 8083
spring:
  datasource:
    #url: jdbc:mariadb://computer-academy-erp.cxdjlccswbih.ap-northeast-2.rds.amazonaws.com:3306/computer_academy_erp
    #url: jdbc:mariadb://computer-academy-erp.cxdjlccswbih.ap-northeast-2.rds.amazonaws.com:3306/test
    url: jdbc:mariadb://localhost:3307/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    #username: nowerp 
    username: root
    #password: nowerp1331 
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  config-location: classpath:mybatis-config.xml